variables:
  PROJECT_NAME: "BaseProjectFlutter"
  IOS_PROJECT_NAME: "Runner"
  FLAVOR: "develop"

include:
  - project: sunflowerlab/operations/pipelines
    ref: flutter-v1.3
    file: 'flutter/stages.yml'
  - project: sunflowerlab/operations/pipelines
    ref: flutter-v1.3
    file: 'flutter/analyse.yml'
  - project: sunflowerlab/operations/pipelines
    ref: flutter-v1.3
    file: 'flutter/archive.yml'
  - project: sunflowerlab/operations/pipelines
    ref: flutter-v1.3
    file: 'flutter/deploy.yml'
